version: "1"

name: deliveroojs

services:

  deliveroojs:

    build:
      dockerfile: Dockerfile
      context: .
    image: deliveroojs

    network_mode: bridge

    restart: unless-stopped

    environment:
      - LEVEL=24c1_1
      - PORT=8080

    ports: # not needed if proxied by caddy
      - "4001:8080"

    labels: # https://github.com/lucaslorentz/caddy-docker-proxy?tab=readme-ov-file#services
      caddy: "deliveroojs24c1_1.rtibdi.disi.unitn.it"
      caddy.reverse_proxy: "{{ upstreams 4001 }}"




